# Generated by Django 4.1.4 on 2023-06-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobileno", models.CharField(max_length=255)),
                ("email", models.EmailField(default="SOME STRING", max_length=254)),
                ("message", models.CharField(default="SOME STRING", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("description", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Dress", "Dress"),
                            ("T-shirt", "T-shirt"),
                            ("Trouser", "Trouser"),
                            ("Jeans", "Jeans"),
                            ("Sweater", "Sweater"),
                            ("Jacket", "Jacket"),
                            ("shirt", "shirt"),
                            ("Coat", "Coat"),
                            ("Boot", "Boot"),
                            ("Bra", "Bra"),
                            ("Swimsuit", "Swimsuit"),
                            ("Gown", "Gown"),
                            ("Slip", "Slip"),
                            ("Wedding dress", "Wedding dress"),
                            ("Sport bra", "Sport bra"),
                            ("Shorts", "Shorts"),
                            ("hoodie", "hoodie"),
                            ("Gym clothes", "Gym clothes"),
                            ("Tank top", "Tank top"),
                            ("Long coat", "Long coat"),
                            ("Uniform", "Uniform"),
                            ("Dress pants", "Dress pants"),
                            ("Skirt", "Skirt"),
                            ("Hat", "Hat"),
                            ("Handbag", "Handbag"),
                            ("Scarf", "Scarf"),
                            ("Kurtas", "Kurtas"),
                            ("Lehenga cholis", "Lehenga cholis"),
                            ("Sarees", "Sarees"),
                        ],
                        max_length=14,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="product")),
                ("brand", models.CharField(max_length=200)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("XXXL", "XXXL"),
                        ],
                        max_length=12,
                    ),
                ),
                ("color", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Customer1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(default="", max_length=200)),
                ("city", models.CharField(default="pune", max_length=50)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh ", "Arunachal Pradesh "),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir ", "Jammu and Kashmir "),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Chandigarh", "Chandigarh"),
                            ("Dadra and Nagar Haveli", "Dadra and Nagar Haveli"),
                            ("Daman and Diu", "Daman and Diu"),
                            ("Lakshadweep", "Lakshadweep"),
                            (
                                "National Capital Territory of Delhi",
                                "National Capital Territory of Delhi",
                            ),
                            ("Puducherry", "Puducherry"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
