# Generated by Django 4.1.4 on 2023-06-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="category_name",
        ),
    ]
