# Generated by Django 4.1.4 on 2023-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_color_alter_product_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Dress", "Dress"),
                    ("T-shirt", "T-shirt"),
                    ("Trouser", "Trouser"),
                    ("Jeans", "Jeans"),
                    ("Sweater", "Sweater"),
                    ("Jacket", "Jacket"),
                    ("shirt", "shirt"),
                    ("Coat", "Coat"),
                    ("Boot", "Boot"),
                    ("Bra", "Bra"),
                    ("Swimsuit", "Swimsuit"),
                    ("Gown", "Gown"),
                    ("Slip", "Slip"),
                    ("Wedding dress", "Wedding dress"),
                    ("Sport bra", "Sport bra"),
                    ("Shorts", "Shorts"),
                    ("hoodie", "hoodie"),
                    ("Gym clothes", "Gym clothes"),
                    ("Tank top", "Tank top"),
                    ("Long coat", "Long coat"),
                    ("Uniform", "Uniform"),
                    ("Dress pants", "Dress pants"),
                    ("Skirt", "Skirt"),
                    ("Hat", "Hat"),
                    ("Handbag", "Handbag"),
                    ("Scarf", "Scarf"),
                    ("Kurtas", "Kurtas"),
                    ("Lehenga cholis", "Lehenga cholis"),
                    ("Sarees", "Sarees"),
                ],
                max_length=14,
            ),
        ),
    ]
